# Generated by Django 4.1 on 2022-08-07 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('language', models.CharField(choices=[('PL', 'polish'), ('ENG', 'english'), ('DE', 'german')], default='ENG', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleDE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='german_article', to='articles.article')),
                ('articleENG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='english_article', to='articles.article')),
                ('articlePL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polish_article', to='articles.article')),
            ],
        ),
    ]
