# Generated by Django 4.1 on 2022-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.CharField(choices=[('K', 'krypto'), ('S', 'securities'), ('SM', 'stock market')], default='K', max_length=2),
        ),
    ]
