# Generated by Django 4.1 on 2022-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_types_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('ETF', 'ETF'), ('IDX', 'indexes'), ('FOR', 'forex'), ('KRY', 'krypto'), ('ACT', 'actions')], default='KRY', max_length=3),
        ),
    ]
